version: '2'

#main app entrypoint
services:
    app:
        build: .
        volumes:
            - '.:/var/www/html'
        ports:
            - '80:80'
            - '443:443'
        tty: true
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        ports:
            - '3306:3306'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: symfony
